server:
  port: 8000

mybatis-plus:
  #xml文件所处位置
  mapper-locations: classpath:com/atguigu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: shop-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.131:8848
  rabbitmq:
    host: 192.168.88.131
    port: 5672
    username: admin
    password: 123
  redis:
    host: 192.168.88.131
    port: 6389
    database: 0
    timeout: 1800000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.131:3306/shop_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    #利用fastjson将数据转为json时会丢失时区
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
minio:
  endpoint: http://192.168.88.131:9000
  access-Key: enjoy6288
  secret-Key: enjoy6288
  bucket-Name: java0518
