server:
  port: 80
spring:
  redis:
    host: 192.168.88.131
    port: 6389
  application:
    name: shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.131:8848
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: shop-product
          uri: lb://shop-product   #nacos中存储的服务名称
          predicates:          #断言
            - Path=/product/** # 路径匹配
        - id: shop-product2
          uri: lb://shop-product   #nacos中存储的服务名称
          predicates:          #断言
            - Path=/sku/** # 路径匹配
        - id: shop-web
          uri: lb://shop-web   #nacos中存储的服务名称
          predicates:          #断言
            - Host=*.gmall.com,127.0.0.1

